version: '3.8'
services:

  stats-server:
    build: ./ewm-stat/stat_server

    image:
      stat_server:latest
    container_name: stat_server_container

    ports:
      - "9090:9090"
      - "9091:9091"

    depends_on:
      - stats_service-db
    environment:
      - STAT_URL_DB=jdbc:postgresql://state_server-db:5432/stat_db
      - STAT_USERNAME_DB=hoiboi
      - STAT_PASSWORD_DB=123321


  stats_service-db:
    image: postgres:15-alpine
    container_name: stat_server-db
    ports:
      - "6666:5432"
    environment:
      - POSTGRES_DB=stat_db
      - POSTGRES_USER=hoiboi
      - POSTGRES_PASSWORD=123321


  ewm-service:
    build: ./ewm-main
    image:
      ewm-service:latest
    container_name: ewm-service_container

    ports:
      - "8080:8080"
      - "8081:8081"

    depends_on:
      - ewm-db
    environment:
      - MAIN_DB=jdbc:postgresql://postgres-main-db:5432/ewm_db
      - MAIN_USER=postgres
      - MAIN_PASSWORD=123321

  ewm-db:
    image: postgres:15
    container_name: postgres-ewm-main-db
    ports:
      - "6464:5432"
    environment:
      - POSTGRES_DB=ewm_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123321